import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Headers from './components/header'
import Hero from './components/hero'
import Services from './components/services'
import TechStack from './components/techStack'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
        <Headers />
      {/* Hero */}
      <Hero />
      <Services />
      <TechStack />
      {/* <header class="bgimg w3-display-container w3-grayscale-min" id="home">
        <div class="w3-display-bottomleft w3-center w3-padding-large w3-hide-small">
          <span class="w3-tag">Open from 6am to 5pm</span>
        </div>
        <div class="w3-display-middle w3-center">
          <span class="w3-text-white" style={{fontSize:'90px'}}>the<br />Cafe</span>
        </div>
        <div class="w3-display-bottomright w3-center w3-padding-large">
          <span class="w3-text-white">15 Adr street, 5015</span>
        </div>
      </header> */}
      {/* About */}

      


    </>

  )
}
