import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Headers from './components/header'
import Hero from './components/hero'
import Services from './components/services'
import TechStack from './components/techStack'
import Projects from './components/projects'
import Contact from './components/contact'
import Footer from './components/footer'
import AboutUs from './components/about'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Savan Padaliya | Full Stack Blockchain developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers />
      <Hero />
      <Services />
      <TechStack />
      <Projects />
      <AboutUs />
      {/* <Contact /> */}
      <Footer />
    </>
  )
}
